version: '3.9'

services:
  mysql_db:
    image: mysql:latest
    restart: unless-stopped
    container_name: node_db
    env_file: ./.env
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db:/var/lib/mysql

  app:
    depends_on:
      - mysql_db
    build: .
    container_name: node_env
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysql_db
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    volumes:
      - .:/express-mysql
    stdin_open: true
    tty: true

volumes:
  db: